"""added role level column

Revision ID: 0804f7804b9a
Revises: 1b489e95df0c
Create Date: 2025-06-01 14:07:25.742120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0804f7804b9a'
down_revision = '1b489e95df0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_level', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.drop_column('role_level')

    # ### end Alembic commands ###
