"""Changes to login schema

Revision ID: 098486dba7d6
Revises: ce92a6751eb5
Create Date: 2025-06-04 07:04:23.741090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '098486dba7d6'
down_revision = 'ce92a6751eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('applications', schema=None) as batch_op:
#         batch_op.alter_column('exam_status',
#                existing_type=sa.VARCHAR(length=20),
#                type_=postgresql.JSONB(astext_type=sa.Text()),
#                existing_nullable=True)
#         batch_op.alter_column('interview_status',
#                existing_type=sa.VARCHAR(length=20),
#                type_=postgresql.JSONB(astext_type=sa.Text()),
#                existing_nullable=True)
#         batch_op.alter_column('status',
#                existing_type=sa.VARCHAR(length=20),
#                type_=postgresql.JSONB(astext_type=sa.Text()),
#                existing_nullable=True)

    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('token',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('interview_status',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('exam_status',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
