"""added is_editable colun in applications table

Revision ID: 3e971ae74fbe
Revises: 80b8c135a89c
Create Date: 2025-06-04 18:22:20.309104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e971ae74fbe'
down_revision = '80b8c135a89c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_editable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('is_editable')

    # ### end Alembic commands ###
