"""Added integrity contraints on applkcation

Revision ID: 6cc94f9421b0
Revises: 7e5d613e7c32
Create Date: 2025-06-13 20:34:43.149744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc94f9421b0'
down_revision = '7e5d613e7c32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('uq_applicant_per_course', ['applicant_id', 'course_id'], unique=True, postgresql_where=sa.text('applicant_id IS NOT NULL'))
        batch_op.create_index('uq_student_per_course', ['student_id', 'course_id'], unique=True, postgresql_where=sa.text('student_id IS NOT NULL'))

    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_section_student', ['course_section_id', 'student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('unique_section_student', type_='unique')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('uq_student_per_course', postgresql_where=sa.text('student_id IS NOT NULL'))
        batch_op.drop_index('uq_applicant_per_course', postgresql_where=sa.text('applicant_id IS NOT NULL'))

    # ### end Alembic commands ###
