"""Chaged datatype of comments in application schema

Revision ID: 7e5d613e7c32
Revises: f77eb2588004
Create Date: 2025-06-06 23:58:22.922638

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7e5d613e7c32"
down_revision = "f77eb2588004"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('applications', schema=None) as batch_op:
    #     batch_op.alter_column('comments',
    #            existing_type=sa.TEXT(),
    #            type_=postgresql.JSONB(astext_type=sa.Text()),
    #            existing_nullable=True)
    op.execute(
        """
        ALTER TABLE applications 
        ALTER COLUMN comments 
        TYPE JSONB 
        USING comments::jsonb;
    """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.alter_column(
            "comments",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
