"""added applications table again

Revision ID: 80b8c135a89c
Revises: 098486dba7d6
Create Date: 2025-06-04 07:14:16.044054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80b8c135a89c'
down_revision = '098486dba7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('exam_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interview_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('submitted_by_type', sa.String(length=10), nullable=False),
    sa.CheckConstraint('(student_id IS NOT NULL AND applicant_id IS NULL) OR (student_id IS NULL AND applicant_id IS NOT NULL)', name='check_one_applicant_type'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
