"""configured some columns of applications table

Revision ID: a61f38b96ec0
Revises: e3cd7a3b4652
Create Date: 2025-05-27 09:19:08.436796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a61f38b96ec0'
down_revision = 'e3cd7a3b4652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('submitted_by_type', sa.String(length=10), nullable=False))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('additional_info')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('application_date')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('cnic',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('father_cnic',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('father_cnic',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('cnic',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('additional_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('submitted_by_type')
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###
