"""added role level column with mdified null constraint

Revision ID: ce92a6751eb5
Revises: 0804f7804b9a
Create Date: 2025-06-01 15:05:21.661886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce92a6751eb5'
down_revision = '0804f7804b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.alter_column('role_level',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.alter_column('role_level',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
