"""Added course logo and banner fields

Revision ID: f120a9d3abb0
Revises: 6cc94f9421b0
Create Date: 2025-06-20 11:50:53.673018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f120a9d3abb0'
down_revision = '6cc94f9421b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logoImg', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bannerImg', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('bannerImg')
        batch_op.drop_column('logoImg')

    # ### end Alembic commands ###
